PregunChaco/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.trivia.urls',namespace='trivia')),    
    path('',include('apps.usuarios.urls',namespace='usuarios')),
    path('',include('apps.resultado.urls',namespace='ranking')), 
    ## mediaConfiguration —— Con la configuración de MEDIA_ROOT en la configuración, puede acceder a la carpeta de medios y a los archivos en la barra de direcciones del navegador
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    #FavIcon    
    re_path(r'^favicon\.ico$', favicon_view),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/usuarios/urls.py
from django.urls import path
from .views import  *
from apps.usuarios import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'apps.usuarios'

urlpatterns = [
    path('registro/', views.registro.as_view(), name='registro'),
    path('login/', LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    #Perfil de usuario
    path('perfil/crear/',CrearPerfil.as_view(),name='crear_perfil'),
    path('<int:pk>/perfil/',VerPerfilView.as_view(),name='perfil'),
    path('<int:pk>/editar_perfil/', UserEditView.as_view(), name='editar_perfil'),
    
]

apps/usuarios/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Perfil(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    email = models.EmailField(default='')
    username = models.CharField(max_length=250, null=True, blank=False)
    first_name = models.CharField(max_length=250, null=True, blank=True)
    last_name = models.CharField(max_length=250, null=True, blank=True)
    creado = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)
    imagen_perfil = models.ImageField(null=True, blank=True, upload_to="perfil/", default='default_profile_pic.png')
    facebook_url = models.TextField(max_length=250, null=True, blank=True)
    twitter_url = models.TextField(max_length=250, null=True, blank=True)
    instagram_url = models.TextField(max_length=250, null=True, blank=True)

    def __str__(self):
        return str(self.user)

apps/usuarios/forms.py
from django.forms.models import ModelForm
from apps.usuarios.models import Perfil
from django import forms
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User

#Redefine el formulario de registro
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)
    

    #Define los campos del Admin en usuarios y limpia el formulario de ayudas
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields }

        def __init__(self, *args, **kwargs):
            super(UserRegisterForm,self).__init__(*args, **kwargs)

            self.fields['username'].widgets.attrs['class'] = 'form-control'
            self.fields['password1'].widgets.attrs['class'] = 'form-control'
            self.fields['password2'].widgets.attrs['class'] = 'form-control'


class CrearPerfil(ModelForm):
    first_name = forms.CharField(required=False,label="Nombre",widget=forms.TextInput)
    last_name = forms.CharField(required=False,label="Apellido",widget=forms.TextInput)
    imagen_perfil = forms.ImageField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_url = forms.URLField(required=False)
    instagram_url = forms.URLField(required=False)
    
    class Meta:
        model = Perfil
        fields = ['first_name','last_name','imagen_perfil','facebook_url','twitter_url','instagram_url']

apps/usuarios/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, UserManager
from django.urls.base import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from apps.usuarios.forms import CrearPerfil, UserRegisterForm
from django.shortcuts import get_object_or_404, render, HttpResponse, redirect, HttpResponseRedirect
from .models import *
from django.urls import reverse_lazy
from django.contrib import messages

class registro(CreateView):
        form_class = UserRegisterForm
        template_name = 'usuarios/registro.html'
        success_url = reverse_lazy('usuarios:login')
        

class UserEditView(UpdateView):
    model = Perfil
    template_name= 'usuarios/editar_perfil.html'    
    fields = ['email','username', 'first_name','last_name','imagen_perfil']
    success_url=reverse_lazy('trivia:home')   

class VerPerfilView(DetailView):
    model = Perfil
    template_name = 'usuarios/perfil.html'

    def get_context_data(self, *args, **kwargs):
        users = Perfil.objects.all()
        context = super(VerPerfilView, self).get_context_data(*args, **kwargs)
        
        user_pag = get_object_or_404(Perfil,id=self.kwargs['pk'])
        
        context["user_pag"] = user_pag
        return context

class CrearPerfil(CreateView):
        form_class = CrearPerfil
        template_name = 'usuarios/crear_perfil.html'
        success_url = reverse_lazy('trivia:home')

        def form_valid(self, form):
            perfil = form.save(commit=False)
            perfil.user = get_object_or_404(User,username=self.request.user)
            perfil.save()
            return HttpResponseRedirect(reverse('trivia:home'))

templates/usuarios/crear_perfil.html
{% extends 'base.html'%}{% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/editar_perfil.css' %}" />
<div class="editar-container">
    <div class="editar-perfil-container">
        <h1 class="title">Crear Perfil:</h1>
        <hr class="linea" />
        <form action="" method="POST" enctype="multipart/form-data" class="inputs-container">
            {% csrf_token %} {{form}}
            <button type="submit" id="submit" class="btn">Guardar</button>

        </form>
        <a class="btn btn-danger text-center" href="/" role="button" id="cancelar">Cancelar</a>
    </div>
</div>
{% endblock %}

templates/usuarios/editar_perfil.html
{% extends 'base.html'%}{% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/editar_perfil.css' %}" />
<div class="editar-container">
    <div class="editar-perfil-container">
        <h1 class="title">Editar Perfil:</h1>
        <hr class="linea" />
        <form action="" method="POST" enctype="multipart/form-data" class="inputs-container">
            {% csrf_token %} {{form.as_p}}
            <button type="submit" id="submit" class="btn">Guardar</button>

        </form>
        <a class="btn btn-danger text-center" href="/" role="button" id="cancelar">Cancelar</a>
    </div>
</div>
{% endblock %}

templates/usuarios/login.html
{% load static %}

<!DOCTYPE html>
<html lang="es-AR">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- TITULO DE LA PÁGINA -->
    <title>PregunChaco Login</title>

    <!-- CSS PRESONALIZADOS -->
    <link rel="stylesheet" href="{% static 'css/cssLogin.css' %}" />
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <div class="login-container">
        <img class="image-container" src="{% static 'imagenes/Logo_PregunChaco_729_376.png' %}" alt="login" /> {% if messages %} {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-sucess" role="alert">
                {{ message }}
            </div>
        </div>
        {%endfor%} {% endif %}
        <div class="login-info-container">
            <h1 class="title">Ingresá con:</h1>

            <form method="post" class="inputs-container form">
                {% csrf_token %} {{ form.as_p }}

                <p>
                    ¿Te olvidaste tu Contraseña?: <span class="span">Click acá</span>
                </p>
                <button type="submit" id="submit" class="btn">Ingresar</button>
                <p>¿No tenés cuenta?: <a class="span" href="{% url 'usuarios:registro'%}">Crea un cuenta</a></p>
            </form>
        </div>
</body>

</html>

templates/usuarios/logout.html
{% extends 'base.html' %}

{% block content %}

<h1>Te has deslogueado</h1>

{% endblock %}

templates/usuarios/perfil.html
{% extends 'base.html'%} {% load static %} {% block content %}

<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{user.perfil.imagen_perfil.url}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{user.username}}</h5>
                <p class="small text-muted">
                    {% if user.perfil.facebook_url%}
                    <a href="{{user.perfil.facebook_url}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                          </svg>
                    </a> | {% endif %} {% if user.perfil.instagram_url%}
                    <a href="{{user.perfil.instagram_url}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                          </svg>
                    </a> | {% endif %} {% if user.perfil.twitter_url%}
                    <a href="{{user.perfil.twitter_url}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                          </svg>
                    </a>
                    {% endif %}
                </p>

                <p class="card-text"><small class="text-muted">Miembro desde: {{user.perfil.creado}}</small></p>
                <p class="card-text"><small class="text-muted">Ultima edicion de perfil: {{user.perfil.updated}}</small></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/usuarios/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="es-AR">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- TITULO DE LA PÁGINA -->
    <title>PregunChaco Registro</title>

    <!-- CSS PRESONALIZADOS -->
    <link rel="stylesheet" href="{% static 'css/cssRegistro.css' %}" />
</head>

<body>
    <div class="login-container">
        <img class="image-container" src="{% static 'imagenes/Logo_PregunChaco_729_376.png' %}" alt="login" />
        <div class="login-info-container">
            <br/>
            <h1 class="title">REGISTRATE AHORA:</h1>
            <form action="" method="post" class="inputs-container">
                {% csrf_token %} {{ form.as_p }}
                <button type="submit" id="submit" class="btn">Ingresar</button>
                <p>
                    ¿Ya tenés cuenta?:
                    <a class="span " href="{% url 'usuarios:login' %}">Ingresá acá</a>
                </p>
            </form>
        </div>
    </div>
</body>

</html>