PregunChaco/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.trivia.urls',namespace='trivia')),    
    path('',include('apps.usuarios.urls',namespace='usuarios')),
    path('',include('apps.resultado.urls',namespace='ranking')), 
    ## mediaConfiguration —— Con la configuración de MEDIA_ROOT en la configuración, puede acceder a la carpeta de medios y a los archivos en la barra de direcciones del navegador
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    #FavIcon    
    re_path(r'^favicon\.ico$', favicon_view),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/resultado/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'apps.resultado'

urlpatterns = [
    path('puntaje',view_puntaje, name="puntaje"),
    path('api/pregunchaco/puntos',validar_puntos,name='Puntaje conseguido'),
    path('api/pregunchaco/scoreboard',scoreboard,name="scoreboard"),
    path('ranking',view_ranking, name="ranking" ),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/trivia/urls.py
from django.urls import path
from .views import *

app_name = 'apps.trivia'

urlpatterns = [
    path('', home, name='home'),
    path('categorias', elegir_categorias, name='categorias'),
    path('api/pregunchaco/',empezar_pregunchaco,name="api_preguntas"),
    path('pregunchaco/',pregunchaco, name="pregunchaco"),
]

apps/usuarios/urls.py
from django.urls import path
from .views import  *
from apps.usuarios import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'apps.usuarios'

urlpatterns = [
    path('registro/', views.registro.as_view(), name='registro'),
    path('login/', LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    #Perfil de usuario
    path('perfil/crear/',CrearPerfil.as_view(),name='crear_perfil'),
    path('<int:pk>/perfil/',VerPerfilView.as_view(),name='perfil'),
    path('<int:pk>/editar_perfil/', UserEditView.as_view(), name='editar_perfil'),
    
]

templates/base.html
{% include 'navbar.html' %} {% load static %} {% load%}
<!DOCTYPE html>
<html lang="es-AR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--LOGO-->
    <div class="container-sm">
        <img style="margin-top: 2rem;" src="{% static '/imagenes/Logo_PregunChaco_729_376.png'%}" class="img-fluid" id="imagen" alt="...">
    </div>

    <!-- ENLACES PARA FAVICON -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icono/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icono/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icono/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icono/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'icono/safari-pinned-tab.svg' %}" color="#5bbad5">
    <link rel="shortcut icon" href="../static/icono/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static 'icono/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
</head>
<!-- VUE JS -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

<link rel="stylesheet" href="/static/css/base.css">

<body background="/media/Fondo_Categorias_1920_1080.png">

    <div id="contenedor-principal" class="container-sm shadow mt-5 mb-2 pt-2 pb-2 rounded-3">
        {% block content %} {% endblock %}
    </div>
</body>{% include 'footer.html' %}

</html>

templates/categorias.html
 {% extends 'base.html' %} {%load static%} {% block content %}

<!--CSS para cada pregunta-->
<style>
    .form-goup {
        margin-top: 15%;
        display: flex;
        flex-direction: column;
        height: 4rem;
        width: 30rem;
    }
    
    .form-select {
        border: 2px solid #134611;
    }
    
    .btn {
        border: 2px solid #134611;
        box-shadow: #134611;
    }
    
    input:focus {
        box-shadow: #134611;
    }
</style>

<form>
    <div class="form-goup">
        <div class="input-group">
            <select name="categoria" class="form-select" id="inputGroupSelect">
              <option selected name="categoria">Elegir una categoria...</option>
              {% for categoria in categorias %}
              <option value="{{categoria.nombre_categoria}}">{{categoria.nombre_categoria}}</option>
              {% endfor %}
            </select>
            <button class="btn btn-success" id="comenzar-btn">¡EMPEZAR!</button>
        </div>
    </div>
</form>
{% endblock %}

templates/footer.html
<footer class="text-center text-white navbarDropdown">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    Informatorio 2021: Trabajo Integrador Final. Comision 5 - Grupo 1
  </div>
  <!-- Informatorio -->
</footer>

templates/home.html
 {% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="/static/css/home.css">

<div class="col-md-4 mt-4">
    <div class="card profile-card-5">
        <div class="card-img-block">
            {% if user.perfil.imagen_perfil.url %}
            <img class="card-img-top" src="{{user.perfil.imagen_perfil.url}}" alt="Card image cap"> {% else%}
            <img class="card-img-top" src="{% static '/imagenes/default_profile_pic.png' %}" alt="Card image cap"> {% endif %}
        </div>


        <div class="card-body pt-0">
            <h5 class="card-title">Hola {{user.username}}</h5>
            <p class="card-text">Bienvenido a PregunChaco</p>

        </div>
    </div>
</div>

</div>
</div>
</section>
{% endblock %}

templates/navbar.html
{% load static %} {% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="{% static '/imagenes/logo.jpg'%}" alt="logo" width="24" height="24" class="d-inline-block align-text-center"> PregunChaco
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    {% if user.perfil.id %}
                    <a class="nav-link" href="{% url 'trivia:categorias' %}">¡Jugar!</a> {%endif%}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a>
                </li>

            </ul>
            <!-- PERFIL-->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{user.first_name}}
                        {{user.last_name}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.perfil.id %}
                        <li><a class="dropdown-item" href="{% url 'usuarios:perfil' user.perfil.id %}">Ver Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'usuarios:editar_perfil' user.perfil.id %}">Editar Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'ranking:puntaje'%}">Tus Puntajes</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'usuarios:crear_perfil'%}">Crear Perfil</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Salir...</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% endblock %}

templates/pregunchaco.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- ESTE HIDDEN INPUT PASA EL NOMBRE DE LA CATEGORIA AL JS-->
<input type="hidden" id="categoria" name="categoria" value="{{categoria}}">

<!--CSS para cada pregunta-->
<link rel="stylesheet" href="/static/css/cartaPregunta.css">

<!--Este modal se activa terminar la trivia-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLabel">{{categoria}}: Puntaje guardado</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3>¡Gracias por jugar!</h3>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="{% url 'ranking:puntaje' %}" role="button">Ver tus resultados</a>
            </div>
        </div>
    </div>
</div>


<div id="app">
    <img v-bind:src="[preguntas[0].logo_categoria]" class="img-fluid" id="logo">
    <form @submit.prevent="enviarResultado()">
        <div class="card">
            <div v-for="(pregunta,index) in preguntas" :key="index ">
                <div class="card-block">
                    </hr>
                    <h5 class="card-title">[[pregunta.pregunta_enunciado]]</h5>
                    <img v-bind:src="[pregunta.imagen]" class="card-img-top" alt="...">
                </div>

                <ul class="list-group list-group-flush">
                    <div class="form-check" v-for="(respuesta,i) in pregunta.respuestas">
                        <li class="list-group-item"> <input @change="checkRespuesta($event,index,i, pregunta.id)" :value="respuesta.respuesta" class="form-check-input" type="radio" :name="'radio-'+pregunta.id" :id="'radio-'+pregunta.id">
                            <label class="form-check-label" for="'radio-'+pregunta.id">
                            [[respuesta.respuesta]] 
                        </label>
                        </li>

                    </div>
                </ul>
                <ul class="list-group list-group-flush">
                    <p :id=" 'mensaje_respuesta-'+pregunta.id "></p>
                    <blockquote class="blockquote">
                        <p :id=" 'dato-'+pregunta.id "></p>
                    </blockquote>
                </ul>
            </div>

        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-danger mt-5" data-bs-toggle="modal" data-bs-target="#exampleModal" type="submit">Terminar</button>
        </div>
    </form>

</div>

<script src="{% static 'apps/trivia.js'%} "></script>
{% endblock content%}

templates/registroTest.html
{% load static %}

<!DOCTYPE html>
<html lang="es-AR">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- TITULO DE LA PÁGINA -->
    <title>PregunChaco Registro</title>

    <!-- CSS PRESONALIZADOS -->
    <link rel="stylesheet" href="{% static 'css/cssRegistro.css' %}" />
  </head>
  <body>
    <div class="login-container">
      <img
        class="image-container"
        src="{% static 'imagenes/Logo_PregunChaco_729_376.png' %}"
        alt="login"
      />
      <div class="login-info-container">
        <h1 class="title">Ingresá con:</h1>
        <div class="social-login">
          <div class="social-login-element">
            <img
              class="imagen-social"
              src="{% static 'imagenes/google.svg' %}"
              alt="google-imagen"
            />
            <span>Google</span>
          </div>
          <div class="social-login-element">
            <img
              class="imagen-social"
              src="{% static 'imagenes/facebook.svg' %}"
              alt="facebook-imagen"
            />
            <span>Facebook</span>
          </div>
        </div>
        <hr class="linea" />
        <form action="" method="post" class="inputs-container">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" id="submit" class="btn">Ingresar</button>
          <p>
            ¿Ya tenés cuenta?:
            <a class="span" href="{% url 'usuarios:login' %}">Ingresá acá</a>
          </p>
        </form>
      </div>
    </div>
  </body>
</html>